name: Deploy

on: [push, workflow_dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PUBLIC_CDN_RES_API_URL: https://stardb.b-cdn.net/api/static
      PUBLIC_SERVER_API_URL: https://stardb.gg/api
      PRIVATE_SERVER_API_URL: https://stardb.gg/api
      PRIVATE_API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install And Build
        run: |
          npm i
          npm run build
          mv node_modules/ build/
          echo '{"type": "module"}' > build/package.json
          mv build stardb-new

      - name: Copy New Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: stardb-new
          target: /root/

      - name: Restart Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            rm -rf stardb
            mv stardb-new stardb
            systemctl restart stardb
